import { FunctionComponent, useEffect, useState } from 'react'
import HelpIcon from '../icons/HelpIcon'
import ThemeIcon from '../icons/ThemeIcon'

const BottomBar: FunctionComponent = () => {
  const LIGHT_THEME = 'cmyk'
  const DARK_THEME = 'sunset'

  const [theme, setTheme] = useState(() => {
    const storedTheme = localStorage.getItem('theme')
    if (storedTheme) {
      return JSON.parse(storedTheme) as string
    } else {
      return 'default'
    }
  })

  useEffect(() => {
    localStorage.setItem('theme', JSON.stringify(theme))
  }, [theme])

  const onHelp = () => {
    const modal = document.getElementById('helpDialog')

    // if we can't find the modal, we should just reroute
    if (modal) {
      const dialog = modal as HTMLDialogElement
      dialog.showModal()
    }
  }

  return (
    <div className="absolute z-10 bottom-0 right-0 m-8">
      <div className="flex gap-4">
        {/* Help */}
        <button className="btn btn-circle text-primary" onClick={onHelp}>
          <HelpIcon />
        </button>

        {/* Theme */}
        <div className="dropdown dropdown-top dropdown-end">
          <div tabIndex={0} role="button" className="btn btn-circle text-primary">
            <ThemeIcon />
          </div>

          <ul
            tabIndex={0}
            className="dropdown-content z-[1] menu p-2 shadow bg-base-200 rounded-box w-52 mb-2"
          >
            <li>
              <input
                type="radio"
                name="theme-dropdown"
                checked={theme == 'default'}
                onChange={() => setTheme('default')}
                className="theme-controller btn btn-sm btn-block btn-ghost justify-start"
                aria-label="Default"
                value="default"
              />
            </li>
            <li>
              <input
                type="radio"
                name="theme-dropdown"
                checked={theme == LIGHT_THEME}
                onChange={() => setTheme(LIGHT_THEME)}
                className="theme-controller btn btn-sm btn-block btn-ghost justify-start"
                aria-label="Light"
                value={LIGHT_THEME}
              />
            </li>
            <li>
              <input
                type="radio"
                name="theme-dropdown"
                checked={theme == DARK_THEME}
                onChange={() => setTheme(DARK_THEME)}
                className="theme-controller btn btn-sm btn-block btn-ghost justify-start"
                aria-label="Dark"
                value={DARK_THEME}
              />
            </li>
          </ul>
        </div>
      </div>

      {/* Help Modal */}
      <dialog id="helpDialog" className="modal">
        <div className="modal-box w-11/12 max-w-5xl">
          <h3 className="font-bold text-lg">Help</h3>
          <p className="pt-4">
            Image Hash Viewer is a small application that allow you to work with various image
            hashes like Average, Difference and Perceptual. It can decode hashes and turn them into
            their original bit matrix and can also hash selected images.
            <br />
            <br />
            For hashing and decoding the app uses{' '}
            <a
              href="https://github.com/yannickalex07/imghash-rs"
              className="text-primary focus outline-none"
            >
              imghash-rs
            </a>
            . The encoding and decoding algorithm of this crate is fully based on the imagehash
            package for Python, therefore this application can also be used to decode hashes
            generated by it.
            <br />
            <br />
            If you want to learn more about how the encoding / decoding as well as the various
            hashing algorithms work, you can visit the GitHub page of imghash-rs.
          </p>
          <div className="modal-action">
            {/* Close Button */}
            <form method="dialog">
              <button className="btn">Close</button>
            </form>
          </div>
        </div>
      </dialog>
    </div>
  )
}

export default BottomBar
